### ISSUE TITLE
LODEX : duplication de la propriété identifiant

### ISSUE THREAD

**Issue by githubroussel** [Inist-CNRS/lodex-v1#12]
Au niveau de l'affichage public des 3 tables :
- http://data-set.lod.istex.fr/
- http://named-entity.lod.istex.fr/
- http://article-type.lod.istex.fr/, 

ll y a duplication de la propriété _identifier_

![image](https://cloud.githubusercontent.com/assets/15609/15826596/7c0406b2-2c08-11e6-907a-3c20e6caafd5.png)

 Utilisation de ces deux propriétés, sachant que nous n'avons retenu que la première  - http://purl.org/dc/terms/identifier et http://purl.org/dc/elements/1.1/identifier
Il nous semblerait pertinent de ne conserver que la première - http://purl.org/dc/terms/identifier
Merci d'avance

**Comment by parmentf** [comment]
J'ai d'ailleurs vu utiliser `dc11` comme préfixe pour http://purl.org/dc/elements/1.1/identifier.
Ici, on ne distingue pas les deux.

Voir [views/themes/istex.html](https://github.com/Inist-CNRS/lodex/blob/b67814d86c70f1cc5c5e638e58fae8cdcbcd45fd/views/themes/istex.html#L63-L64)
