### ISSUE TITLE
Liens internes Jeux  de données 

### ISSUE THREAD

**Issue by githubroussel** [Inist-CNRS/lodex-v1#14]
A partir de la page d'accueil du Blog (http://lodex.inist.fr/), en choisissant Jeux de données le lien descendant (ou horizontal comme boucle sur lui même?) destination finale feuille vide avec la mention 
Pas de résultat (Faîtes attention quand vous utilisez plusieurs facettes) inutile voire scorie.

De plus je n'ai pas trouvé comment remonter jusqu'à la page initiale Jeux de données

Sur la page Jeux de données angle gauche en haut, texte corriger de façon adaptée 
No available description

**Comment by parmentf** [comment]
Voir l'issue #15
