### ISSUE TITLE
Liens descendants Jeux de données

### ISSUE THREAD

**Issue by githubroussel** [Inist-CNRS/lodex-v1#15]
En cliquant sur http://article-type.lod.istex.fr/, on parvient sur la page de la table Article-type qui contient le tableau des 10 items de la table.
Le lien pour chaque item renvoie à une page destination finale feuille vide avec la mention 
`Pas de résultat (Faîtes attention quand vous utilisez plusieurs facettes)` inutile voire scorie.
Le lien `GO UP` renvoie également à cette page.
Ceci est reproductible pour chaque table contenue dans data set (Jeux de données)
Il est donc impossible de naviguer entre les tables Jeux de données et les tables contenues par ce jeu ou de quitter une table.

**Comment by parmentf** [comment]
Actuellement, ce widget essaye d'afficher le nombre de documents dans le corpus istex dont le `genre.raw` (type de publication) correspond au champ `englishLabel` du JSON-LD (c'est-à-dire à la colonne dont le nom technique est `englishLabel`).

D'ailleurs je pense que si actuellement, dans la table `t3`, on changeait le nom technique de la colonne nommée `Identifiant` et dont le nom technique est bizarrement `_description`, ce widget marcherait.

Voir [le code](https://github.com/Inist-CNRS/lodex/blob/master/views/item.html#L34).

C'était pour un MVP.

Maintenant, il faudrait pouvoir le configurer en lui donnant:
- la facette ISTEX dans laquelle on veut chercher(voir [Recherche avancée](https://api.istex.fr/documentation/300-search.html#recherche-avancee) dans la documentation de l'API ISTEX)
- l'URI du champ dans le JSON-LD qu'on veut trouver dans le corpus ISTEX
