### ISSUE TITLE
Ingestion table Article-type

### ISSUE THREAD

**Issue by githubroussel** [Inist-CNRS/lodex-v1#16]
A l’issue du chargement de la table Article-type, on constate que contrairement au contenu des colonnes du tableau validé avec l’équipe Istex-data, les définitions anglaises n’apparaissent pas donc pas non plus le lien vers la ressource native de la NLM.

**Comment by parmentf** [comment]
Oui, les propriétés affichées ne tiennent pas compte des langues, et n'affiche que la première rencontrée (dans ce cas, les propriétés françaises apparaissent avant les anglaises):
![image](https://cloud.githubusercontent.com/assets/595509/16305901/1bc4c8e8-395c-11e6-9157-640ea63b1a91.png)

JSON-LD correspondant:
![image](https://cloud.githubusercontent.com/assets/595509/16305950/4cfc9828-395c-11e6-9108-f266a1a37073.png)
