### ISSUE TITLE
Navigation  Named-entity

### ISSUE THREAD

**Issue by githubroussel** [Inist-CNRS/lodex-v1#17]
Lorsque l’on clique dans la page http://named-entity.lod.istex.fr/ sur le lien 
GO UP  http://data-set.lod.istex.fr/=/entitee-nommee  
on obtient le message d’erreur suivant
 Le serveur web renvoie une erreur interne.

[Datamodel.mongoDatabaseHandle] connect ECONNREFUSED et il est impossible de s'en échapper

**Comment by parmentf** [comment]
Oui, c'était dû à une maintenance du serveur: la base de données n'était plus en route.
C'est maintenant corrigé.
