### ISSUE TITLE
Affichage du texte dans les colonnes des jeux de données

### ISSUE THREAD

**Issue by githubroussel** [Inist-CNRS/lodex-v1#18]
Dans les tableaux excel dédiés aux différents jeux de données, l'intitulé des colonnes peut être long, très long, voire trop long....réfléchir, proposer et valider un nombre de caractères limités en premier affichage et un lire la suite ou voir plus pour accéder au texte intégral

**Comment by parmentf** [comment]
De ce que j'avais compris, c'est plus le contenu des cellules dans les colonnes qui peuvent être trop longs, et donc générer une mise en page déséquilibrée, augmentant la hauteur de certaines lignes.

Par exemple sur http://named-entity.lod.istex.fr/ :
![lodex-named-entity-issue18](https://cloud.githubusercontent.com/assets/595509/15970656/030a0afa-2f36-11e6-805e-3b863039ad1b.png)

N'afficher qu'une partie tronquée (à une longueur à déterminer) tout en proposant de déplier la cellule résoudrait le problème (et même, plus simple en supposant qu'on a accès aux données complètes de la ligne en cliquant dessus, sans même proposer le dépliage)...
