### ISSUE TITLE
modification de colonne dans une table : rejet en fin de table

### ISSUE THREAD

**Issue by githubroussel** [Inist-CNRS/lodex-v1#28]
Lorsque l'on intervient sur une colonne pendant ou après chargement de la table concernée, la colonne concernée est systématiquement rejetée en fin de table c'est à dire à l'extrémité droite.

**Comment by parmentf** [comment]
Cette *issue* ne concerne pas ezmaster, mais lodex.
Elle est dans le mauvais dépôt.
