### ISSUE TITLE
Translation files are wrongly located when lodex is run by ezmaster

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex-v1#3]
When you run `lodex` from anywhere out of the source directory, the `locales` directory created by `i18n-2` is created in the current working directory (and also, it does not use the one in the package directory).

Thus, no translation is taken into account...

**Comment by touv** [comment]
fixed in https://github.com/castorjs/castor-core/commit/db132064c2e290c8322b17645a81356797b82ee3
