### ISSUE TITLE
NO_PROXY setting

### ISSUE THREAD

**Issue by parmentf** [Inist-CNRS/lodex-v1#32]
When my `NO-PROXY` (and `no_proxy`) variable is set to `localhost,127.0.0.0/8,::1`, as it is by default on my machine, I got only errors on default page:

```
The following error was encountered while trying to retrieve the URL: http://127.0.0.1:3000/data_P_7LCAAWQ

\n\n
\n
Connection to 127.0.0.1 failed.
\n
\n\n
The system returned: (111) Connection refused

\n\n
The remote host or network may be down. Please try the request again.
```

**Comment by touv** [comment]
fix in castor-8.4.2 see here https://github.com/castorjs/castor-core/blob/master/starter.js#L17-L29
