### ISSUE TITLE
Inist-category supprimé par erreur

### ISSUE THREAD

**Issue by cecifabry** [Inist-CNRS/lodex-v1#39]
sorry sorry j'ai raté mon coup
et je sais pas défaire ce que j'ai fait

**Comment by kerphi** [comment]
tu peux récupérer sa dernière version ici :)
https://raw.githubusercontent.com/Inist-CNRS/lodex/a9fd55f208ec0ecc83ce4cb85168729007c1d9d4/example/inist-category.json

**Comment by touv** [comment]
voilà c'est récupéré
https://github.com/Inist-CNRS/lodex/commit/f7b2dd9212e703f7fcdc0d17e8cd6820aef98dc8

**Comment by cecifabry** [comment]
Thanks :+1:
